### ISSUE TITLE
Update to latest version

### ISSUE THREAD

**Issue by mirenradia** [flathub/io.github.mimbrero.WhatsAppDesktop#1]
Hello, I noticed there have been some new releases (1.2.3 and 1.2.3-1) in [mimbrero/whatsapp-desktop-linux](https://github.com/mimbrero/whatsapp-desktop-linux/releases) but the Flatpak hasn't been updated here. Would it be possible to update it?

**Comment by mimbrero** [comment]
I was just doing that xd, thanks. 😄
